### ISSUE TITLE
How to resolve Polyfill issue with @what3words/api

### ISSUE THREAD

**Issue by VashJuan** [what3words/w3w-node-wrapper#40] opened 2022-02-05 15:53 UTC
Using latest of Angular/etc. I get:

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

I'm trying to figure out WHERE to add these lines, but figure you might know?!

Thx.

**Comment by VashJuan** [comment] 2022-02-05 16:08
More at https://github.com/angular/angular-cli/issues/20819, but I'm still wandering in unfamiliar land for me...

**Comment by c5haw** [comment] 2022-02-21 13:09
@VashJuan Hi, I'm not entirely following the issue you've reported here. Could you please provide more detail and any code snippets to reproduce please?

**Comment by VashJuan** [comment] 2022-02-21 14:40
Sorry I didn't leave you with much did I? I'll be retrying in the next week and will provide more details (& not under my previous deadline) to clarify.

**Comment by c5haw** [comment] 2022-06-17 10:12
Closing due to lack of detail to troubleshoot and action.

**Closed by c5haw** 2022-06-17 10:12 UTC
